export const COMPANY = {
  name: "Asmaa Design Kitchen",
  nameAr: "أسماء ديزاين كيتشن",
  phone: "01003994843",
  phoneFormatted: "+20 100 399 4843",
  email: "asmaahossam97@gmail.com",
  whatsapp: "https://wa.me/201003994843",
  facebook: "https://facebook.com/asmaadesignkitchen",
  instagram: "https://instagram.com/asmaadesignkitchen",
  tiktok: "https://tiktok.com/@asmaadesignkitchen",
  address: "التجمع الخامس، القاهرة الجديدة، مصر",
  addressEn: "5th Settlement, New Cairo, Egypt",
  mapUrl: "https://maps.google.com/?q=30.0274,31.4913",
  mapEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d55251.37!2d31.4!3d30.03!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMzDCsDAxJzM4LjYiTiAzMcKwMjknMjguNyJF!5e0!3m2!1sar!2seg!4v1700000000000",
  hours: {
    weekdays: "9:00 AM - 9:00 PM",
    friday: "2:00 PM - 9:00 PM",
    saturday: "9:00 AM - 9:00 PM",
  },
};

export const IMAGES = {
  hero: "https://images.pexels.com/photos/36511381/pexels-photo-36511381.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
  modernKitchen: "https://images.pexels.com/photos/8082304/pexels-photo-8082304.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  classicKitchen: "https://images.pexels.com/photos/8141955/pexels-photo-8141955.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  whiteKitchen: "https://images.pexels.com/photos/6207824/pexels-photo-6207824.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  luxuryKitchen: "https://images.pexels.com/photos/7045826/pexels-photo-7045826.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  closet: "https://images.pexels.com/photos/7031842/pexels-photo-7031842.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  dressingRoom: "https://images.pexels.com/photos/7195887/pexels-photo-7195887.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  dressingRoom2: "https://images.pexels.com/photos/7195738/pexels-photo-7195738.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  classicDining: "https://images.pexels.com/photos/3229076/pexels-photo-3229076.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  kitchen2: "https://images.pexels.com/photos/20348120/pexels-photo-20348120.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  kitchen3: "https://images.pexels.com/photos/7535011/pexels-photo-7535011.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  kitchen4: "https://images.pexels.com/photos/6332975/pexels-photo-6332975.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
  drawerDetail: "https://images.pexels.com/photos/38311093/pexels-photo-38311093.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
};

export const NAV_ITEMS = [
  { href: "/", label: "الرئيسية", labelEn: "Home" },
  { href: "/services", label: "خدماتنا", labelEn: "Services" },
  { href: "/gallery", label: "معرض الأعمال", labelEn: "Gallery" },
  { href: "/about", label: "من نحن", labelEn: "About" },
  { href: "/blog", label: "المدونة", labelEn: "Blog" },
  { href: "/offers", label: "العروض", labelEn: "Offers" },
  { href: "/calculator", label: "حاسبة التكلفة", labelEn: "Calculator" },
  { href: "/contact", label: "تواصل معنا", labelEn: "Contact" },
];

export const SERVICES = [
  {
    id: "modern-kitchens",
    title: "مطابخ مودرن",
    titleEn: "Modern Kitchens",
    description: "تصميم وتنفيذ مطابخ مودرن بأحدث الخامات والتشطيبات العالمية. نقدم تصاميم عصرية تجمع بين الأناقة والعملية.",
    image: "https://images.pexels.com/photos/8082304/pexels-photo-8082304.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "ChefHat",
  },
  {
    id: "classic-kitchens",
    title: "مطابخ كلاسيك",
    titleEn: "Classic Kitchens",
    description: "مطابخ كلاسيكية فاخرة بتفاصيل دقيقة ونقوشات أنيقة. خشب طبيعي عالي الجودة مع لمسات ذهبية مميزة.",
    image: "https://images.pexels.com/photos/8141955/pexels-photo-8141955.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Crown",
  },
  {
    id: "dressing-rooms",
    title: "دريسنج روم",
    titleEn: "Dressing Rooms",
    description: "تصميم وتنفيذ غرف ملابس عصرية بأفضل حلول التخزين الذكية. مساحات مرتبة وأنيقة تناسب احتياجاتك.",
    image: "https://images.pexels.com/photos/7195887/pexels-photo-7195887.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Shirt",
  },
  {
    id: "tv-units",
    title: "وحدات تلفزيون",
    titleEn: "TV Units",
    description: "وحدات تلفزيون مودرن وعصرية بتصاميم مبتكرة. تجمع بين الجمال والتنظيم مع إضاءة مخفية أنيقة.",
    image: "https://images.pexels.com/photos/6332975/pexels-photo-6332975.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Tv",
  },
  {
    id: "closets",
    title: "كلوزيت",
    titleEn: "Closets",
    description: "خزائن ملابس عملية وأنيقة بأحدث أنظمة التخزين. تصاميم تستغل كل سنتيمتر من المساحة المتاحة.",
    image: "https://images.pexels.com/photos/7031842/pexels-photo-7031842.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "DoorOpen",
  },
  {
    id: "custom-furniture",
    title: "أثاث حسب الطلب",
    titleEn: "Custom Furniture",
    description: "تصنيع أثاث خشبي حسب الطلب بأعلى معايير الجودة. نحول أفكارك إلى قطع أثاث فريدة تعكس ذوقك.",
    image: "https://images.pexels.com/photos/3229076/pexels-photo-3229076.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Armchair",
  },
  {
    id: "interior-wood",
    title: "نجارة و تشطيبات داخلية",
    titleEn: "Interior Wood Design",
    description: "أعمال نجارة داخلية متكاملة من الأبواب والشبابيك إلى البانوهات والديكورات الخشبية الفاخرة.",
    image: "https://images.pexels.com/photos/7535011/pexels-photo-7535011.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Hammer",
  },
  {
    id: "3d-design",
    title: "تصميم مطابخ 3D",
    titleEn: "3D Kitchen Design",
    description: "نقدم تصميم ثلاثي الأبعاد لمطبخك قبل التنفيذ. شاهد مطبخك الجديد بتفاصيله الكاملة قبل بدء التصنيع.",
    image: "https://images.pexels.com/photos/20348120/pexels-photo-20348120.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    icon: "Box",
  },
];

export const GALLERY_ITEMS = [
  { id: 1, src: IMAGES.modernKitchen, category: "modern", title: "مطبخ مودرن فاخر" },
  { id: 2, src: IMAGES.classicKitchen, category: "classic", title: "مطبخ كلاسيك خشب" },
  { id: 3, src: IMAGES.whiteKitchen, category: "luxury", title: "مطبخ أبيض فاخر" },
  { id: 4, src: IMAGES.luxuryKitchen, category: "modern", title: "مطبخ مودرن أبيض" },
  { id: 5, src: IMAGES.closet, category: "closets", title: "كلوزيت عصري" },
  { id: 6, src: IMAGES.dressingRoom, category: "closets", title: "دريسنج روم" },
  { id: 7, src: IMAGES.classicDining, category: "classic", title: "مطبخ كلاسيك مع سفرة" },
  { id: 8, src: IMAGES.kitchen2, category: "luxury", title: "مطبخ رخام فاخر" },
  { id: 9, src: IMAGES.kitchen3, category: "classic", title: "مطبخ كلاسيك أبيض" },
  { id: 10, src: IMAGES.kitchen4, category: "modern", title: "مطبخ مودرن خشب" },
  { id: 11, src: IMAGES.drawerDetail, category: "modern", title: "تفاصيل مطبخ مودرن" },
  { id: 12, src: IMAGES.dressingRoom2, category: "closets", title: "خزانة ملابس بيضاء" },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "أحمد محمد",
    location: "القاهرة الجديدة",
    text: "تجربة ممتازة من البداية للنهاية. التصميم كان أكثر من رائع والتنفيذ احترافي جداً. أنصح الجميع بالتعامل مع أسماء ديزاين.",
    rating: 5,
  },
  {
    id: 2,
    name: "سارة أحمد",
    location: "التجمع الخامس",
    text: "مطبخي أصبح تحفة فنية! الخامات عالية الجودة والتركيب كان سريع ودقيق. شكراً لفريق العمل المتميز.",
    rating: 5,
  },
  {
    id: 3,
    name: "محمد علي",
    location: "مدينة نصر",
    text: "أفضل شركة مطابخ تعاملت معها. الأسعار تنافسية جداً مقارنة بالجودة العالية. التسليم كان في الموعد بالظبط.",
    rating: 5,
  },
  {
    id: 4,
    name: "فاطمة حسن",
    location: "الشروق",
    text: "عملت مطبخي ودريسنج روم من عند أسماء ديزاين وكانت النتيجة فوق التوقعات. تصميم ثلاثي الأبعاد ساعدني أختار الأنسب.",
    rating: 5,
  },
  {
    id: 5,
    name: "كريم عبدالله",
    location: "الرحاب",
    text: "من أحسن القرارات اللي اتخذتها إني اتعاملت مع أسماء ديزاين. جودة عالية وسعر ممتاز وضمان على الشغل.",
    rating: 5,
  },
];

export const PROCESS_STEPS = [
  { step: 1, title: "التواصل", titleEn: "Contact", description: "تواصل معنا عبر الهاتف أو الواتساب", icon: "Phone" },
  { step: 2, title: "استشارة مجانية", titleEn: "Free Consultation", description: "نقدم لك استشارة مجانية لفهم احتياجاتك", icon: "MessageCircle" },
  { step: 3, title: "معاينة الموقع", titleEn: "Site Visit", description: "زيارة الموقع وأخذ المقاسات الدقيقة", icon: "MapPin" },
  { step: 4, title: "تصميم 3D", titleEn: "3D Design", description: "تصميم ثلاثي الأبعاد لرؤية النتيجة النهائية", icon: "Monitor" },
  { step: 5, title: "التصنيع", titleEn: "Manufacturing", description: "تصنيع في مصنعنا الخاص بأعلى المعايير", icon: "Factory" },
  { step: 6, title: "التركيب", titleEn: "Installation", description: "تركيب احترافي بواسطة فنيين متخصصين", icon: "Wrench" },
  { step: 7, title: "التسليم", titleEn: "Delivery", description: "تسليم المشروع في الموعد المحدد مع ضمان شامل", icon: "CheckCircle" },
];

export const BLOG_POSTS = [
  {
    id: "modern-kitchen-trends-2024",
    title: "أحدث صيحات المطابخ المودرن",
    titleEn: "Modern Kitchen Trends",
    excerpt: "اكتشف أحدث التصاميم والألوان والخامات في عالم المطابخ المودرن لعام 2024.",
    content: "المطابخ المودرن أصبحت الخيار الأول للعديد من الأسر المصرية. تتميز بالخطوط النظيفة والألوان العصرية واستخدام أحدث التقنيات في التخزين والإضاءة.",
    image: IMAGES.modernKitchen,
    date: "2024-01-15",
    category: "trends",
  },
  {
    id: "kitchen-materials-guide",
    title: "دليل خامات المطابخ: MDF vs HPL vs PVC",
    titleEn: "Kitchen Materials Guide",
    excerpt: "مقارنة شاملة بين أنواع خامات المطابخ المختلفة لمساعدتك في اختيار الأنسب.",
    content: "اختيار الخامة المناسبة لمطبخك من أهم القرارات. نقارن بين MDF و HPL و PVC من حيث الجودة والسعر والمتانة.",
    image: IMAGES.drawerDetail,
    date: "2024-02-01",
    category: "materials",
  },
  {
    id: "kitchen-colors-2024",
    title: "ألوان المطابخ الرائجة",
    titleEn: "Trending Kitchen Colors",
    excerpt: "أفضل ألوان المطابخ التي تناسب الذوق المصري والعربي مع نصائح التنسيق.",
    content: "الألوان تلعب دوراً كبيراً في جعل مطبخك مكاناً مريحاً وجذاباً. نستعرض أحدث الألوان الرائجة.",
    image: IMAGES.whiteKitchen,
    date: "2024-02-15",
    category: "design",
  },
  {
    id: "kitchen-maintenance-tips",
    title: "نصائح للحفاظ على مطبخك",
    titleEn: "Kitchen Maintenance Tips",
    excerpt: "نصائح عملية للحفاظ على مطبخك نظيفاً ولامعاً لسنوات طويلة.",
    content: "العناية بمطبخك تضمن بقاءه في أفضل حال لسنوات. نقدم لك أهم النصائح للتنظيف والصيانة.",
    image: IMAGES.kitchen2,
    date: "2024-03-01",
    category: "maintenance",
  },
];
